services:
#    mysql:
#        container_name: "rfsim5g-mysql"
#        image: mysql:8.0
#        volumes:
#            - ../5g_rfsimulator/oai_db.sql:/docker-entrypoint-initdb.d/oai_db.sql
#            - ../5g_rfsimulator/mysql-healthcheck.sh:/tmp/mysql-healthcheck.sh
#        environment:
#            - TZ=Europe/Paris
#            - MYSQL_DATABASE=oai_db
#            - MYSQL_USER=test
#            - MYSQL_PASSWORD=test
#            - MYSQL_ROOT_PASSWORD=linux
#        healthcheck:
#            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
#            interval: 10s
#            timeout: 5s
#            retries: 30
#        networks:
#            core_net:
#                ipv4_address: 192.168.71.131
#                ipv4_address: 172.22.0.131
#    oai-amf:
#        container_name: "rfsim5g-oai-amf"
#        image: oaisoftwarealliance/oai-amf:v2.0.0
#        environment:
#            - TZ=Europe/paris
#        volumes:
#            - ./mini_nonrf_config_3slices.yaml:/openair-amf/etc/config.yaml
#        depends_on:
#            - mysql
#        networks:
#            core_net:
#                ipv4_address: 192.168.71.132
#                ipv4_address: 172.22.0.10
#    oai-smf:
#        container_name: "rfsim5g-oai-smf"
#        image: oaisoftwarealliance/oai-smf:v2.0.0
#        environment:
#            - TZ=Europe/Paris
#        volumes:
#            - ./mini_nonrf_config_3slices.yaml:/openair-smf/etc/config.yaml
#        depends_on:
#            - oai-amf
#        networks:
#            core_net:
#                ipv4_address: 192.168.71.133
#                ipv4_address: 172.22.0.7
#    oai-upf:
#        container_name: "rfsim5g-oai-upf"
#        image: oaisoftwarealliance/oai-upf:v2.0.0
#        environment:
#            - TZ=Europe/Paris
#        volumes:
#            - ./mini_nonrf_config_3slices.yaml:/openair-upf/etc/config.yaml
#        depends_on:
#            - oai-smf
#        cap_add:
#            - NET_ADMIN
#            - SYS_ADMIN
#        cap_drop:
#            - ALL
#        privileged: true
#        networks:
#            core_net:
#                ipv4_address: 192.168.71.134
#                ipv4_address: 172.22.0.8
#            traffic_net:
#                ipv4_address: 192.168.72.134

    oai-cucp:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-oai-cucp
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --sa --log_config.global_log_options level,nocolor,time
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.77.2
                                    --gNBs.[0].local_s_address 192.168.72.2
            ASAN_OPTIONS: detect_leaks=0
#        depends_on:
#            - oai-upf
        networks:
            default:
                ipv4_address: 172.22.0.23
            f1c_net:
                ipv4_address: 192.168.72.2
            e1_net:
                ipv4_address: 192.168.77.2
        volumes:
            - ./gnb-cucp.sa.f1.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-cuup:
        image: oaisoftwarealliance/oai-nr-cuup:develop
        container_name: rfsim5g-oai-cuup
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --sa --log_config.global_log_options level,nocolor,time
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cucp 192.168.77.2
                                    --gNBs.[0].E1_INTERFACE.[0].ipv4_cuup 192.168.77.3
                                    --gNBs.[0].local_s_address 192.168.73.2
                                    --gNBs.[0].remote_s_address 127.0.0.1
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-cucp
        networks:
            default:
#                ipv4_address: 192.168.71.161
                ipv4_address: 172.22.0.50
            f1u_1_net:
                ipv4_address: 192.168.73.2
            e1_net:
                ipv4_address: 192.168.77.3
        volumes:
            - ./gnb-cuup.sa.f1.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-cuup"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-du:
        image: oaisoftwarealliance/oai-gnb:develop
        container_name: rfsim5g-oai-du
        cap_drop:
            - ALL
        environment:
            USE_ADDITIONAL_OPTIONS: --sa --rfsim --log_config.global_log_options level,nocolor,time
                                    --MACRLCs.[0].local_n_address 192.168.72.3
                                    --MACRLCs.[0].remote_n_address oai-cucp
                                    --MACRLCs.[0].local_n_address_f1u 192.168.73.3
            ASAN_OPTIONS: detect_leaks=0
        depends_on:
            - oai-cucp
            - oai-cuup
        networks:
            f1c_net:
                ipv4_address: 192.168.72.3
            f1u_1_net:
                ipv4_address: 192.168.73.3
            ue_net:
                ipv4_address: 192.168.78.2
        volumes:
            - ./gnb-du.sa.band78.106prb.rfsim.conf:/opt/oai-gnb/etc/gnb.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-softmodem"
            interval: 10s
            timeout: 5s
            retries: 5

    oai-nr-ue:
        image: oaisoftwarealliance/oai-nr-ue:develop
        container_name: rfsim5g-oai-nr-ue
        cap_drop:
            - ALL
        cap_add:
            - NET_ADMIN  # for interface bringup
            - NET_RAW    # for ping
        environment:
            USE_ADDITIONAL_OPTIONS: --sa --rfsim --log_config.global_log_options level,nocolor,time
                                    -r 106 --numerology 1 -C 3619200000
                                    --uicc0.imsi 208990100001100
                                    --rfsimulator.serveraddr 192.168.78.2
        depends_on:
            - oai-du
        networks:
            ue_net:
                ipv4_address: 192.168.78.5
        devices:
             - /dev/net/tun:/dev/net/tun
        volumes:
            - ./nrue.uicc.conf:/opt/oai-nr-ue/etc/nr-ue.conf
        healthcheck:
            test: /bin/bash -c "pgrep nr-uesoftmodem"
            interval: 10s
            timeout: 5s
            retries: 5
networks:
#    core_net:
#        driver: bridge
#        name: rfsim5g-oai-core-net
#        ipam:
#            config:
#                - subnet: 172.22.0.0/24
#        driver_opts:
#            com.docker.network.bridge.name: "rfsim5g-core"
    default:
        external:
            name: docker_open5gs_default
    traffic_net:
        driver: bridge
        name: rfsim5g-oai-traffic-net
        ipam:
            config:
                - subnet: 192.168.72.128/26
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-traffic"
    f1c_net:
        driver: bridge
        name: rfsim5g-oai-f1c-net
        ipam:
            config:
                - subnet: 192.168.72.0/28
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-f1c"
    f1u_1_net:
        driver: bridge
        name: rfsim5g-oai-f1u-1-net
        ipam:
            config:
                - subnet: 192.168.73.0/28
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-f1u_1"
    e1_net:
        driver: bridge
        name: rfsim5g-oai-e1-net
        ipam:
            config:
                - subnet: 192.168.77.0/28
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-e1"
    ue_net:
        driver: bridge
        name: rfsim5g-oai-ue-net
        ipam:
            config:
                - subnet: 192.168.78.0/28
        driver_opts:
            com.docker.network.bridge.name: "rfsim5g-ue"


